### ISSUE TITLE
Error 401 Please login

### ISSUE THREAD

**Issue by ETGermany** [zapccu/ioBroker.sma-ev-charger#18]
**Describe the bug**  
After a power failure of the EV-Charger, the instances must be restarted.

**To Reproduce**  
1. Making EV-Chargers currentless
2. Reconnecting EV-Chargers
3. See error log

**Expected behavior**  
A new login to the EV-Charger is required

**Screenshots & Logfiles**  
![sma-ev-charger Error](https://github.com/zapccu/ioBroker.sma-ev-charger/assets/132834418/9dcab663-316b-4a92-8aa5-0b4af95f3887)

**Versions:**  
 - Adapter version: 0.1.5
 - JS-Controller version: 4.0.24 
 - Node version: 14.21.1 
 - Operating system: Windows 11

**Additional context**

**Comment by zapccu** [comment]
Seems that EV charger is invalidating the refresh token after power failure or restart. Thank you for the hint!

**Comment by zapccu** [comment]
Latest version in repository is solving this issue. The adapter is now trying to reconnect / relogin to SMA EV Charger when an update or token refresh failed.

**Comment by ETGermany** [comment]
Thanks a lot, my test was successful.

 

Von: zapccu ***@***.***> 
Gesendet: Donnerstag, 13. Juli 2023 13:44
An: zapccu/ioBroker.sma-ev-charger ***@***.***>
Cc: ETGermany ***@***.***>; Author ***@***.***>
Betreff: Re: [zapccu/ioBroker.sma-ev-charger] Error 401 Please login (Issue #18)

 

Closed #18 <https://github.com/zapccu/ioBroker.sma-ev-charger/issues/18>  as completed.
